# Generated by Django 5.2.5 on 2025-08-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('league', models.CharField(max_length=100)),
                ('teams', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('results', models.CharField(blank=True, max_length=50, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'VIP Tip',
                'verbose_name_plural': 'VIP',
                'ordering': ['-date_posted'],
            },
        ),
    ]
