# Generated by Django 5.2.5 on 2025-08-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='access_code',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
